[theme]
primaryColor = "#FF8C42"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F5F5F5"
textColor = "#5A6C7D"
font = "sans serif"

[server]
headless = true
port = 8501

[browser]
gatherUsageStats = false
